
project_id = "nwzgipryovjsombsqbdv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[functions]
[functions.create-payment-intent]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = true
