// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwzgipryovjsombsqbdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53emdpcHJ5b3Zqc29tYnNxYmR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2MDQ3OTIsImV4cCI6MjA1NjE4MDc5Mn0.Bt0Fj2QafTosEfeQEz34xi3KZgEZa0i_mKUP8W9NawM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);